replicaCount: 2

image:
  tag: "d925f34182d7bc2ba6e708c8cae289ec1bd355c6"

ingress:
  enabled: true
  hosts:
    - host: app.iqbalhakim.ink
      paths:
        - path: /
          pathType: Prefix
    - host: iqbalhakim.ink
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
