apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kube-prometheus-stack-grafana
  namespace: monitoring
spec:
  dataFrom:
    - extract:
        key: monitoring/staging/kube-prometheus-stack-grafana
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-kube-prometheus-stack-alertmanager
  namespace: monitoring
spec:
  dataFrom:
    - extract:
        key: monitoring/staging/alertmanager-kube-prometheus-stack-alertmanager
