apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-token
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: cloudflare-token
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: external-dns/cloudflare-token
        property: CF_API_TOKEN
