apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kube-prometheus-stack-grafana
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: kube-prometheus-stack-grafana
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: monitoring/kube-prometheus-stack-grafana
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-kube-prometheus-stack-alertmanager
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: alertmanager-kube-prometheus-stack-alertmanager
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: monitoring/alertmanager-kube-prometheus-stack-alertmanager
