apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argo-rollouts.yaml
  - frontend.yaml
  - backend.yaml
  - metrics-server.yaml
  - cert-manager.yaml
  - external-dns.yaml
  - external-secrets.yaml
  - grafana.yaml
  - istio.yaml
  - tailscale.yaml
  - alert.yaml
  - argo-image-updater.yaml
