replicaCount: 2

image:
  tag: "70431fb945bc752f2c74204e6795f22f2f4257df"

ingress:
  enabled: true
  hosts:
    - host: api.iqbalhakim.ink
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

topologySpreadConstraints:
- maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: DoNotSchedule
  labelSelector:
    matchLabels:
      app.kubernetes.io/name: backend
